go_slack_bot:
  image: chomey/go_slack_bot:localdev
  ports:
    - "9090:9090"
  volumes:
    - ./logs/:/var/log/
  environment:
    - RC_HOSTNAME=localhost
    - SLACK_TOKEN=$SLACK_TOKEN
    - SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN