go-slack-bot:
  image: chomey/go-slack-bot:dev
  ports:
    - "1102:1102"
  volumes:
    - ./development-env.json:/app/go-slack-bot-env.json
    - ./logs/:/var/log/
  environment:
    - RC_HOSTNAME=localhost